# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avctl < Formula
  desc ""
  homepage "https://github.com/fetchai/avctl"
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/fetchai/avctl/releases/download/v0.1.5/avctl_Darwin_x86_64.tar.gz"
      sha256 "414d72aeeb58c3f405b8d72877d9f3184409ea309a4558066ecc8e2e96fc0e16"

      def install
        bin.install "avctl"
      end
    end
    on_arm do
      url "https://github.com/fetchai/avctl/releases/download/v0.1.5/avctl_Darwin_arm64.tar.gz"
      sha256 "428c3074e469e080bc7c49d384e3d470526ec4a4d8c3e95151da6c564b4cada2"

      def install
        bin.install "avctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fetchai/avctl/releases/download/v0.1.5/avctl_Linux_x86_64.tar.gz"
        sha256 "83e1e3a185d79704419c33afb74daf580951323dd39b142e2fb7188a65361d5b"

        def install
          bin.install "avctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fetchai/avctl/releases/download/v0.1.5/avctl_Linux_arm64.tar.gz"
        sha256 "0a625034285c37f00eaa3fc8f23fdbe4674f17aee8a4910dcde61c205b25ffb8"

        def install
          bin.install "avctl"
        end
      end
    end
  end
end
