# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avctl < Formula
  desc ""
  homepage "https://github.com/fetchai/avctl"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.15/avctl_Darwin_x86_64.tar.gz"
      sha256 "6f2069f5ea9d9cb99467d88ad3625213c3fdf4c0ef51b81aa703d3194f924297"

      def install
        bin.install "avctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.15/avctl_Darwin_arm64.tar.gz"
      sha256 "bbf5491e21fffbd608718857a09b43cced52ecf70bf18cdfb163627325d81546"

      def install
        bin.install "avctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.15/avctl_Linux_x86_64.tar.gz"
      sha256 "fd2ee8eca6b7d3334c17e5d9ca7dddc27df3c9c2f0a11c458e504e26cb4ba1cd"
      def install
        bin.install "avctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.15/avctl_Linux_arm64.tar.gz"
      sha256 "7cb1227d7a7c4cd0cd1626b634934d87046df0733d21469209b5ce2a26a9cfb8"
      def install
        bin.install "avctl"
      end
    end
  end
end
