# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avctl < Formula
  desc ""
  homepage "https://github.com/fetchai/avctl"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.2/avctl_Darwin_x86_64.tar.gz"
      sha256 "dd1f2a87c7cff90c9ddc1ebf46b26c921e5e3a9feaed518ab9289f64772c9ddb"

      def install
        bin.install "avctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.2/avctl_Darwin_arm64.tar.gz"
      sha256 "4654e34ee3a6dbe2a67fa823285880671f86ca2c1789c3ff54b0af8b52c5aafb"

      def install
        bin.install "avctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.2/avctl_Linux_x86_64.tar.gz"
      sha256 "4063c6747a79781596e9ed43d34b1e02ec0c9a18a1b5b8ce0b56577f52b96ebf"

      def install
        bin.install "avctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fetchai/avctl/releases/download/v0.1.2/avctl_Linux_arm64.tar.gz"
      sha256 "8748815dae643763e905caac72b7f44f071f46b5c55ba95f876896c23e531448"

      def install
        bin.install "avctl"
      end
    end
  end
end
